version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.4
    ports:
      - '3306:3306'
    environment:
      - MARIADB_ROOT_PASSWORD=simplepassword
      - MARIADB_DATABASE=myapp
  myapp:
    image: docker.io/bitnami/codeigniter:4
    ports:
      - '8080:8000'
    environment:
      - CODEIGNITER_DATABASE_HOST=mariadb
      - CODEIGNITER_DATABASE_PORT_NUMBER=3306
      - CODEIGNITER_DATABASE_USER=root
      - CODEIGNITER_DATABASE_NAME=myapp
      - CODEIGNITER_DATABASE_PASSWORD=d0notenter
    volumes:
      - '.:/app'
    depends_on:
      - mariadb
